#!/bin/env python3
from json import loads, dumps
from sys import argv, stdin, stdout

from common import build, check

build(argv[1:])
loaded_ir = loads(stdin.read())
stdout.write(dumps({k: v for k, v in loaded_ir.items() if not check(k)}))
