#!/usr/bin/env python
import json
import sys
input_path = sys.argv[1]

with open(input_path, "r") as input_file:
    loaded_json = json.load(input_file)
    for key in loaded_json.keys():
        if "displayName" in loaded_json[key]:
            displayName = loaded_json[key]["displayName"]
            loaded_json[key]["displayName"] = displayName if not displayName.startswith("[ ") else displayName[2:]
with open(input_path, "w") as output_file:
    json.dump(loaded_json, output_file)
