#!/usr/bin/env python
import json
import os
import sys

json_path = sys.argv[1]
output_path = sys.argv[2]
flag = sys.argv[3] == "kotlin"

with (open(json_path, 'r') as json_file):
    source_map = json.load(json_file)
    json_dir = os.path.dirname(json_path)
    source_map["sources"] = \
        [os.path.abspath(os.path.join(json_dir, ".." if flag else ".", x)) for x in source_map["sources"]]
    with open(output_path, 'w') as output_file:
        json.dump(source_map, output_file)
